#!/bin/sh

exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
#exec 1>log.out 2>&1

show_usage() {
	echo "Usage:"
	echo "    xbps-mini-builder [-f|--force]"
	echo "    -f|--force        build packages even if not updated since last build"
}

force_build=
while :; do
	case $1 in
		-f|--force)
			force_build=1
			shift
			;;
		-h|--help)
			show_usage
			exit
			;;
		*)
			break
	esac
done

# Jump to the directory that owns this script
cd "${0%/*}" || exit 1

# Do we have keys to sign with?
if [ ! -f $HOME/id_rsa ] ; then
	>&2 echo "No RSA keys found to sign with."
	return 1
fi

# Remove old state
rm -f changed

# Create the void-packages directory if it doesn't exit
mkdir -p void-packages
cd void-packages || exit 2

# Do we actually have the repo yet?
if [ ! -d srcpkgs ] ; then
	# No, clone a fresh copy
	git clone https://github.com/void-linux/void-packages .

	# On bootstrap we need to build everything
	cp ../packages.list ../changed
else
	# Yes, pull in the changes for this run
	git reset --hard HEAD
	git pull | tee ../changed
	if [ -s "$force_build" ]; then
		cat packages.list >> ../changed
	fi
fi

# Does this system use another set of repos
if [ -d /etc/xbps.d ] ; then
	cat /etc/xbps.d/*.conf > etc/repos-remote.conf
	# If this platform is 64 bit, override those as well
	if [ "$(xbps-uhelper arch)" = "x86_64" ] ; then
		cat /etc/xbps.d/*.conf > etc/repos-remote-x86_64.conf
	fi

	# The bootstrap config is loaded seperately
	if [ -f /etc/xbps.d/00-repository-main.conf ] ; then
		repo="$(sed 's/^.*=//' < /etc/xbps.d/00-repository-main.conf)"
		printf 'XBPS_INSTALL_ARGS="--repository=%s --repository=%s/musl"\n' "${repo}" "${repo}" > etc/conf
	fi
fi

# Do we have a live build environment
if [ ! -d masterdir ] ; then
	# No masterdir, go ahead and bootstrap it
	/xbps-src binary-bootstrap
else
	# Have a masterdir, keep it up to date
	/xbps-src bootstrap-update
fi

# Apply provided config file if it exists
if [ -f ../xbps-src.conf ] ; then
	cat ../xbps-src.conf >> etc/conf
fi

if [ -z "$@" ] ; then
	while read -r package ; do
		if grep "${package}" ../changed; then
			./xbps-src pkg "${package}"
		fi
	done < ../packages.list
else
	for pkg in "$@"; do
		./xbps-src pkg "${pkg}"
	done
fi

binpkg_files_present () {
	if [[ -d "hostdir/binpkgs/${1}" -a -f "hostdir/binpkgs/${1}"/*.xbps ]]; then
		return 0
	else
		return 1
	fi
}

# # Sign built packages
# if binpkg_files_present; then
#     xbps-rindex --sign --signedby "XBPS-mini-builder" --privkey ../id_rsa hostdir/binpkgs
#     xbps-rindex --sign-pkg --privkey ../id_rsa hostdir/binpkgs/*.xbps
# fi

for folder in "" multilib multilib/nonfree nonfree ; do
	printf "Trying to sign packages in %s\\n" ${folder}
	if binpkg_files_present ${folder} ; then
		printf "Updating repodata in hostdir/binpkgs/%s\\n" ${folder}
		xbps-rindex --sign --signedby "XBPS-mini-builder" --privkey $HOME/id_rsa "hostdir/binpkgs/${folder}"
		printf "Signing packages in hostdir/binpkgs/%s\\n" ${folder}
		xbps-rindex --sign-pkg --privkey $HOME/id_rsa hostdir/binpkgs/${folder}*.xbps
	fi
done
